### ISSUE TITLE
Pulp-cli-0.23.1 not compatible with pulp.squeezer:0.0.14

### ISSUE THREAD

**Issue by AlessandroTaufer** [pulp/squeezer#141]
Lastest pulp-cli version (as today `pulp-cli-0.23.1`) is not compatible with the latest pulp3 squeezer module (`pulp.squeezer:0.0.14`).

It returns the following error when invoking the playbook:

`ImportError: Installed 'pulp-glue' version 0.23.1 is not in >=0.20.0,<0.22.0`

**Comment by mdellweg** [comment]
For reasons of sanity, we need to keep an upper bound on the supported versions at all time. Do you think, apart from obviously trying to update that range, the error message could be improved?

**Comment by AlessandroTaufer** [comment]
Nope, I think the error message is well done and understandable. As you said, the issue is only related to the range. 

Isn't there a way you could coordinate the release of the `pulp-cli` (and consequently the `pulp-glue`) and the `squeezer` module? I'm not really into your workflows so I understand I might not be possible. 

Though, it would be very cool if the features of squeezer were aligned with the cli ones. In my personal experience most of the CI automations are based on squeezer

**Comment by mdellweg** [comment]
It's more like squeezer does not get the amount of love it deserves, because work = power * time.
OTOH I am absolutely not comfortable having an open version rage here, because I know I will have breaking changes in the CLI.
Would you be willing to experiment with the newer version and open a PR for it?

**Comment by AlessandroTaufer** [comment]
Sure, why not. 
Are you already aware of some breaking changes that I might find?

**Comment by mdellweg** [comment]
> Are you already aware of some breaking changes that I might find?

No particular ones.
