### ISSUE TITLE
deb_remote: add support for sync_installer and sync_udebs

### ISSUE THREAD

**Issue by achevalet** [pulp/squeezer#152]
`sync_installer` and `sync_udebs` are required to sync installer files and packages:
https://docs.pulpproject.org/pulp_deb/restapi.html#tag/Remotes:-Apt/operation/remotes_deb_apt_create

Any plan to support them? It would be great. Thanks.

**Comment by mdellweg** [comment]
I would be happy to see a PR. Preferably with test coverage.

**Comment by joey-grant** [comment]
@mdellweg, I have submitted a pull request for this issue: https://github.com/pulp/squeezer/pull/172

Let me know if anything needs to be tweaked.
