### ISSUE TITLE
rpm_repository/retain_repo_versions

### ISSUE THREAD

**Issue by asphalter** [pulp/squeezer#165]
We'd like to specify how many repositories versions to keep online, but even if this param could be found out on pulp_cli, I can't find it either on squeezer.

Could you please verify and let me know?

Brief functional desc from the official pulp's doc:
"Provided by pulpcore, specifies how many repository versions will be kept for a repository. For example, if set to 1, it will keep only the most-recent repository version; the rest will be automatically deleted, together with any associated publications. Note, however, that repository versions that are currently being distributed are "protected", and cannot be removed. This can result in more versions being retained than specified by retain_repo_versions."

**Comment by joey-grant** [comment]
Hey @asphalter. I saw this comment of yours and verified that the option does not exist in version `0.16`. I submitted a pull request to add this option.

https://github.com/pulp/squeezer/pull/171#issue-2430941461
