### ISSUE TITLE
add client auth options to rpm_remote module

### ISSUE THREAD

**Issue by keilr** [pulp/squeezer#55]
We would like to automate the creation of our RHEL remote repositories. To do this, we need to be able to pass the client cert and key as well as the CA cert.

Pulp API doc: [Create a rpm remote](https://pulp-rpm.readthedocs.io/en/latest/restapi.html#operation/remotes_rpm_rpm_create)

@cognifloyd: Could you help us with this?

**Comment by keilr** [comment]
@mdellweg: are issues for this project tracked on github or plan.io?

**Comment by mdellweg** [comment]
Issues are collected here. I don't have the capacity to work on this one however. PR's are still always welcome.

**Comment by mdellweg** [comment]
@keilr, I'v started a PR on this. It would be very helpful, if you could start to test this out early.
I'm having trouble with recording the tests for it.
