### ISSUE TITLE
As a user I can set a boolean value to the autopublish attribute with the rpm_repository module

### ISSUE THREAD

**Issue by ajsween** [pulp/squeezer#62]
The pulp_rpm ([3.12](https://github.com/pulp/pulp_rpm/blob/3.13/CHANGES.rst#features-1) [Issue # 7622](https://pulp.plan.io/issues/7622)) plugin added support for ```autopublish``` as a boolean attribute when creating and updating RPM repositories. However, the REST API documentation has not been published/generated since v3.7 and errors out for the [latest](https://pulp-rpm.readthedocs.io/en/latest/restapi.html) tag. The built-in API explorer for pulp does show the new attribute.

**Comment by mdellweg** [comment]
Where's the Rest API docs you are referring to?

**Comment by ajsween** [comment]
Only visible by running pulp with the pulp_rpm plugin and navigating to /pulp/api/v3

**Comment by mdellweg** [comment]
> Only visible by running pulp with the pulp_rpm plugin and navigating to /pulp/api/v3

Sorry, i meant the outdated one. Maybe you are looking in the wrong place:
https://docs.pulpproject.org/pulp_rpm/restapi.html#operation/repositories_rpm_rpm_create

And much more likely, we forgot to take down the outdated ones.
@ggainey @goosemania ^

**Comment by ajsween** [comment]
Old REST API documentation (last work version I had found via the version navigator at the bottom of the read the docs page)
https://pulp-rpm.readthedocs.io/en/3.7/restapi.html

Latest pulp_rpm docs have a side bar link to REST API
https://pulp-rpm.readthedocs.io/en/latest/

But it is a broken link
https://pulp-rpm.readthedocs.io/en/latest/restapi.html

**Comment by mdellweg** [comment]
Confirmed: The new home of the docs is https://docs.pulpproject.org/pulp_rpm/
