### ISSUE TITLE
Create rpm remote with pulp.squeezer.rpm_remote fails

### ISSUE THREAD

**Issue by jbcreek** [pulp/squeezer#70]
Using pulp.squeezer.rpm_remote to list the remotes works.  Creating an rpm remote with pulp.squeezer.rpm_remote fails

pulp/squeezer version 0.0.9
Ansible 2.10.11

The full traceback is:                                                                                                             
Traceback (most recent call last):

  File "/tmp/ansible_pulp.squeezer.rpm_remote_payload_n0d4601z/ansible_pulp.squeezer.rpm_remote_payload.zip/ansible_collections/pulp/squeez
er/plugins/modules/rpm_remote.py", line 115, in main

  File "/tmp/ansible_pulp.squeezer.rpm_remote_payload_n0d4601z/ansible_pulp.squeezer.rpm_remote_payload.zip/ansible_collections/pulp/squeez
er/plugins/module_utils/pulp.py", line 282, in process
    self.find()

  File "/tmp/ansible_pulp.squeezer.rpm_remote_payload_n0d4601z/ansible_pulp.squeezer.rpm_remote_payload.zip/ansible_collections/pulp/squeez
er/plugins/module_utils/pulp.py", line 163, in find
    search_result = self.module.pulp_api.call(self._list_id, parameters=parameters)

  File "/tmp/ansible_pulp.squeezer.rpm_remote_payload_n0d4601z/ansible_pulp.squeezer.rpm_remote_payload.zip/ansible_collections/pulp/squeez
er/plugins/module_utils/openapi.py", line 217, in call
    method, path = self.operations[operation_id]

KeyError: 'remotes_rpm_rpm_list'
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "ca_cert": null,
            "client_cert": null,
            "client_key": null,
            "download_concurrency": null,
            "name": "CentOS 7-3",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "policy": "on_demand",
            "proxy_password": null,
            "proxy_url": null,
            "proxy_username": null,
            "pulp_url": "https://192.168.183.55",
            "refresh_api_cache": false,
            "remote_password": null,
            "remote_username": null,
            "state": "present",
            "tls_validation": null,
            "url": "https://mirror.wdc1.us.leaseweb.net/centos/7/os/x86_64/",
            "username": "admin",
            "validate_certs": false
        }
    },
    "msg": "'remotes_rpm_rpm_list'"

**Comment by mdellweg** [comment]
sorry, this must have escaped my attention.
It sounds to me like pulp_rpm was not installed on the server. Can you confirm that? Is this still valid?

**Comment by Raptus1** [comment]
Hi @mdellweg,

I get a similar message, but for python plugin:

{
  "changed": false,
  "exception": "Traceback (most recent call last):
  File \"/tmp/ansible_pulp.squeezer.python_repository_payload_lv1kow_6/ansible_pulp.squeezer.python_repository_payload.zip/ansible_collections/pulp/squeezer/plugins/modules/python_repository.py\", line 94, in main
  File \"/tmp/ansible_pulp.squeezer.python_repository_payload_lv1kow_6/ansible_pulp.squeezer.python_repository_payload.zip/ansible_collections/pulp/squeezer/plugins/module_utils/pulp.py\", line 295, in process
    self.find()
  File \"/tmp/ansible_pulp.squeezer.python_repository_payload_lv1kow_6/ansible_pulp.squeezer.python_repository_payload.zip/ansible_collections/pulp/squeezer/plugins/module_utils/pulp.py\", line 163, in find
    search_result = self.module.pulp_api.call(self._list_id, parameters=parameters)
  File \"/tmp/ansible_pulp.squeezer.python_repository_payload_lv1kow_6/ansible_pulp.squeezer.python_repository_payload.zip/ansible_collections/pulp/squeezer/plugins/module_utils/openapi.py\", line 217, in call
    method, path = self.operations[operation_id]

KeyError: 'repositories_python_python_list'
",
  "msg": "'repositories_python_python_list'",
  "invocation": {
    "module_args": {
      "pulp_url": "https://something.net",
      "username": "user",
      "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
      "name": "PyPi",
      "state": "present",
      "validate_certs": true,
      "refresh_api_cache": false,
      "description": null
    }
  },
  "_ansible_no_log": false
}

Plugin is installed with pulp_installer playbook:

TASK [pulp.pulp_installer.pulp_common : Install Pulp plugins via PyPI] *********
ok: [something.net] => (item={'key': 'pulp-ansible', 'value': {'version': '0.14.2'}})
ok: [something.net] => (item={'key': 'pulp-file', 'value': {'version': '1.11.1'}})
ok: [something.net] => (item={'key': 'pulp-container', 'value': {'version': '2.14.0'}})
ok: [something.net] => (item={'key': 'pulp-rpm', 'value': {'prereq_role': 'pulp.pulp_installer.pulp_rpm_prerequisites', 'version': '3.18.1'}})
ok: [something.net] => (item={'key': 'pulp-python', 'value': {'version': '3.7.2'}})



Using pulp cli works:

pulp python repository create --name PyPi

squeeze-module still fails after manually adding with cli.

I would also like to add that things work fine when using squeezer against container on same install.

**Comment by mdellweg** [comment]
Can you confirm that `pulp debug openapi operation --id repositories_python_python_list` returns something meaningful?
Can you also try to delete the api-cache? (Use `refresh_api_cache: true` as a mosule parameter.)
Dumb question: Sure you re talking to the same server? Does the output of the status module report the python plugin?

**Comment by Raptus1** [comment]
Thank you for the quick reply!

This is the response I got in return.

```
pulp debug openapi operation --id repositories_python_python_list
{
  "method": "get",
  "path": "/pulp/api/v3/repositories/python/python/",
  "operation": {
    "operationId": "repositories_python_python_list",
    "description": "PythonRepository represents a single Python repository, to which content can be\nsynced, added, or removed.",
    "summary": "List python repositorys",
    "parameters": [
      {
        "name": "limit",
        "required": false,
        "in": "query",
        "description": "Number of results to return per page.",
        "schema": {
          "type": "integer"
        }
      },
      {
        "in": "query",
        "name": "name",
        "schema": {
          "type": "string"
        }
      },
      {
        "in": "query",
        "name": "name__contains",
        "schema": {
          "type": "string"
        },
        "description": "Filter results where name contains value"
      },
      {
        "in": "query",
        "name": "name__icontains",
        "schema": {
          "type": "string"
        },
        "description": "Filter results where name contains value"
      },
      {
        "in": "query",
        "name": "name__in",
        "schema": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "description": "Filter results where name is in a comma-separated list of values",
        "explode": false,
        "style": "form"
      },
      {
        "in": "query",
        "name": "name__startswith",
        "schema": {
          "type": "string"
        },
        "description": "Filter results where name starts with value"
      },
      {
        "name": "offset",
        "required": false,
        "in": "query",
        "description": "The initial index from which to return the results.",
        "schema": {
          "type": "integer"
        }
      },
      {
        "in": "query",
        "name": "ordering",
        "schema": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "-addons",
              "-alternatecontentsourcepath",
              "-ansible_ansiblerepository",
              "-container_containerpushrepository",
              "-container_containerrepository",
              "-content",
              "-core_pulp_exporter",
              "-description",
              "-distributions",
              "-file_filerepository",
              "-group_roles",
              "-name",
              "-next_version",
              "-pk",
              "-pulp_created",
              "-pulp_id",
              "-pulp_labels",
              "-pulp_last_updated",
              "-pulp_type",
              "-pulpimporterrepository",
              "-python_pythonrepository",
              "-remote",
              "-repositorycontent",
              "-retain_repo_versions",
              "-rpm_rpmrepository",
              "-uploads",
              "-user_hidden",
              "-user_roles",
              "-variants",
              "-versions",
              "addons",
              "alternatecontentsourcepath",
              "ansible_ansiblerepository",
              "container_containerpushrepository",
              "container_containerrepository",
              "content",
              "core_pulp_exporter",
              "description",
              "distributions",
              "file_filerepository",
              "group_roles",
              "name",
              "next_version",
              "pk",
              "pulp_created",
              "pulp_id",
              "pulp_labels",
              "pulp_last_updated",
              "pulp_type",
              "pulpimporterrepository",
              "python_pythonrepository",
              "remote",
              "repositorycontent",
              "retain_repo_versions",
              "rpm_rpmrepository",
              "uploads",
              "user_hidden",
              "user_roles",
              "variants",
              "versions"
            ]
          }
        },
        "description": "Ordering",
        "explode": false,
        "style": "form"
      },
      {
        "in": "query",
        "name": "pulp_label_select",
        "schema": {
          "type": "string"
        },
        "description": "Filter labels by search string"
      },
      {
        "in": "query",
        "name": "remote",
        "schema": {
          "type": "string",
          "format": "uuid"
        },
        "description": "Foreign Key referenced by HREF"
      },
      {
        "in": "query",
        "name": "fields",
        "schema": {
          "type": "string"
        },
        "description": "A list of fields to include in the response."
      },
      {
        "in": "query",
        "name": "exclude_fields",
        "schema": {
          "type": "string"
        },
        "description": "A list of fields to exclude from the response."
      }
    ],
    "tags": [
      "Repositories: Python"
    ],
    "security": [
      {
        "cookieAuth": []
      },
      {
        "basicAuth": []
      }
    ],
    "responses": {
      "200": {
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/Paginatedpython.PythonRepositoryResponseList"
            }
          }
        },
        "description": ""
      }
    }
  }
}
```


I will try your refresh api theory :)

**Comment by Raptus1** [comment]
Sure looks like `refresh_api_cache: true` did the trick.

```
TASK [configure_pulp : CONFIG.REPOS - [CREATE REPO: PyPi ]] ****************10:25:01
Tuesday 20 September 2022  08:25:01 +0000 (0:00:00.184)       0:00:03.782 *****
ok: [something.net]

TASK [configure_pulp : CONFIG.REMOTE - [CREATE REMOTE: PyPi ]] *************10:25:06
Tuesday 20 September 2022  08:25:06 +0000 (0:00:05.197)       0:00:08.979 *****
ok: [something.net]

TASK [configure_pulp : CONFIG.DISTRIBUTION - [SETUP: PyPi ]] ***************10:25:12
Tuesday 20 September 2022  08:25:12 +0000 (0:00:05.699)       0:00:14.679 *****
ok: [something.net]
```

all ok as I ran it twice to check.

Maybe this issue is the case for @jbcreek as well. 

Thank you very much @mdellweg!

**Comment by mdellweg** [comment]
You are welcome. I can only assume it _is_ the same issue. I am going to close it then.
