### ISSUE TITLE
Improve instructions for development

### ISSUE THREAD

**Issue by markgoddard** [pulp/squeezer#76]
There are some instructions in the README for development, however there were definitely some parts left as an exercise for the reader. Here's what I did:

```
# Install deps
python3 -m venv venv
source venv/bin/activate
make test-setup

# Modify run_container.sh to run a Pulp in one container in the background
sed -i 's/^trap/#trap/' tests/run_container.sh
```

I then used the following script to record:

```
#!/bin/bash

set -ex

for m in repository remote sync distribution; do
    sudo docker rm -f pulp || true
    sudo rm -rf tests/settings/certs
    ./tests/run_container.sh
    make record_container_$m
done
sudo docker rm -f pulp || true
```

And this to test:

```
#!/bin/bash

set -ex

for m in repository remote sync distribution; do
    make test_container_$m
done
```

Eventually I worked out that you could do this (if you don't change the run_container.sh script):

```
./tests/run_container.sh make livetest_container_repository
```

However it fails if you run it again because the pulp container still exists (need to `docker rm -f pulp`).

**Comment by mdellweg** [comment]
Thank you for the feedback. I usually record against a vm. But this container based approach is def an interesting addition to the toolbox. Regarding removing the container, this is a bit of a problem. The `run_container.sh` is really designed to run in the CI, and we need the container there to live after the tests, so we can call docker logs in the after_failure stage.
